/*jshint unused: false*/

MainState.SHOW_FULL_SYNC = 'SHOW_FULL_SYNC';
MainState.SHOW_CONNECT_TODOIST = 'SHOW_CONNECT_TODOIST';
MainState.EXIT_APP = 'EXIT_APP';
MainState.SHOW_NO_INTERNET = 'SHOW_NO_INTERNET';
MainState.SHOW_CREATE_TASK_LOAD = 'SHOW_CREATE_TASK_LOAD';
MainState.HIDE_LOAD = 'HIDE_LOAD';
MainState.SHOW_LOAD = 'SHOW_LOAD';
MainState.SHOW_TASK_MENU = 'SHOW_TASK_MENU';
MainState.SHOW_DELETE_CONFIRMATION = 'SHOW_DELETE_CONFIRMATION';

function MainState() {
}